// 20151128191541
// http://www.curatist.co/feed/river/design

export default {
    "res": [
    {
        "id": "0006776",
        "summary": "continue reading",
        "title": "They wanted to show off their skills in steel construction, so they built this…",
        "link": "http://feedproxy.google.com/~r/contemporist/~3/a56lW8NwCVo/",
        "feed": "CONTEMPORIST",
        "published": "Sat, 28 Nov 2015 22:59:49 GMT",
        "image": "http://www.contemporist.com/wp-content/uploads/2015/11/steel-construction_281115_01.jpg?1ff4a6",
        "diff": "an hour",
        "websiteUrl": "http://www.contemporist.com",
        "websiteDesc": "Contemporary Modern Architecture Furniture Lighting Interior Design",
        "whenLastUpdate": "Sat, 28 Nov 2015 23:06:36 GMT"
    },
    {
        "id": "0006775",
        "summary": "Alpine Modern First Edition Sticker Pack -  Features prints found in their Café in Boulder. The iconic hex moose, hex campfire, AM logo, Typographic Mountain and Mountain Icon.  (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "Alpine Modern First Edition Sticker Pack -...",
        "link": "http://www.notcot.org/post/60627/",
        "feed": "NOTCOT.ORG",
        "published": "Sat, 28 Nov 2015 16:51:01 GMT",
        "image": "http://www.notempire.com/images/uploads/stickers-8.jpg",
        "diff": "an hour",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Sat, 28 Nov 2015 23:06:34 GMT"
    },
    {
        "id": "0006764",
        "summary": "a series of concrete forms overlooking the waterfront contain tea houses of varying sizes offering a range of privacy and access to several courtyards.\nThe post DnA architecture and design casts concrete damushan tea house appeared first on designboom | architecture &amp; design ...",
        "title": "DnA architecture and design casts concrete damushan tea house",
        "link": "http://www.designboom.com/architecture/dna-architecture-and-design-damushan-tea-house-china-11-28-2015/",
        "feed": "designboom",
        "published": "Sat, 28 Nov 2015 22:15:48 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/DnA_damushanteahouse_db_01.jpg",
        "diff": "2 hours",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Sat, 28 Nov 2015 22:21:24 GMT"
    },
    {
        "id": "0006760",
        "summary": "UPDATE: The Deadline has been extended to Wednesday, December 3rd at 9:00 AM EST. ArchDaily is looking for motivated architecture geeks to join our team of interns for Spring 2016! An ArchDaily internship is a great opportunity to learn about our site and get exposed to some ...",
        "title": "Call for ArchDaily Interns: Spring 2016",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/zjQ4sLWRiKw/call-for-archdaily-interns-spring-2016",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 21:15:00 GMT",
        "image": "http://images.adsttc.com/media/images/5644/ed0d/e58e/ce94/e500/01b3/medium_jpg/ADGlobalCallForInterns.jpg?1447357704",
        "diff": "2 hours",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 21:52:28 GMT"
    },
    {
        "id": "0006749",
        "summary": "A picturesque lake in Hampshire, England, is the setting for this fisherman's hut by Niall McLaughlin Architects, which can be opened up in summer and battened down in winter (+ slideshow). (more&hellip;)",
        "title": "Niall McLaughlin's Hampshire Fishing Hut folds open to allow views right through",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/p4xQJGTNf90/",
        "feed": "Dezeen",
        "published": "Sat, 28 Nov 2015 21:00:39 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/The-Fishing-Hut_Hampshire_Niall-McLaughlin-Architects_dezeen_sqb2.jpg",
        "diff": "3 hours",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Sat, 28 Nov 2015 21:07:32 GMT"
    },
    {
        "id": "0006748",
        "summary": "Harold Washington Library Center by Hammond, Beeby &amp; Babka. Image © flickr user juggernautco, licensed under CC BY 2.0\n\nPostmodern architecture has largely been overlooked in recent years, left behind by current fashion, but not quite old enough to gain the attention of ...",
        "title": "Chicago's Overlooked Postmodern Architecture",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/6iaWyvzpb7w/chicagos-overlooked-postmodern-architecture",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 21:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5656/972e/e58e/ceb2/5f00/029c/medium_jpg/7979597534_853b707358_o.jpg?1448515360",
        "diff": "3 hours",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 21:07:26 GMT"
    },
    {
        "id": "0006737",
        "summary": "with a set goal to avoid embellishment, electronics, and plastic, the design team instead aimed at loading each piece with imagination and simplicity.\nThe post huzi design presents cosmos magnetic wooden toy collection appeared first on designboom | architecture &amp; design ...",
        "title": "huzi design presents cosmos magnetic wooden toy collection",
        "link": "http://www.designboom.com/design/huzi-design-cosmos-toy-collection-11-28-2015/",
        "feed": "designboom",
        "published": "Sat, 28 Nov 2015 20:30:20 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/huzidesigndesignboom01.jpg",
        "diff": "4 hours",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Sat, 28 Nov 2015 20:36:19 GMT"
    },
    {
        "id": "0006727",
        "summary": "This house is a minimum house for young couples built along the riverside of Ochiaigawa of Higashikurume, Tokyo prefecture, in Japan. It is built in the environment that is full of the green that was adjacent in Ochiaigawa, and it's white and simple volume like a \"TOFU\" ...",
        "title": "Small core house of Ochiaigawa",
        "link": "http://architizer.com/projects/small-core-house-of-ochiaigawa/",
        "feed": "Architizer",
        "published": "Sat, 28 Nov 2015 20:06:26 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/7a/c7/7ac7eccdeb51a46c05e7b5e6c5a82ba0.jpg",
        "diff": "4 hours",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Sat, 28 Nov 2015 20:06:26 GMT"
    },
    {
        "id": "0006689",
        "summary": "Triggertrap - app and dongles to turn your phone into a controller for your camera! Timelapses made easy. Whistle, clap, apple watch and more to control your shutter! And the packaging is even better than you'd expect.  (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "Triggertrap - app and dongles to turn your...",
        "link": "http://www.notcot.org/post/60626/",
        "feed": "NOTCOT.ORG",
        "published": "Sat, 28 Nov 2015 12:20:02 GMT",
        "image": "http://www.notempire.com/images/uploads/rigger.jpg",
        "diff": "6 hours",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Sat, 28 Nov 2015 18:21:20 GMT"
    },
    {
        "id": "0006688",
        "summary": "Music: paper puppeteer and animator Winston Hacking has created a series of moving collages for the video to accompany Soupcans' Siamese Brutality track. (more&hellip;)",
        "title": "Winston Hacking creates absurd paper puppets for Soupcans' Siamese Brutality music video",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/RCojsDygo5w/",
        "feed": "Dezeen",
        "published": "Sat, 28 Nov 2015 18:00:59 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Music-Video_Soupcans_Siamese-Brutality_Winston-Hacking_dezeen_sqa.gif",
        "diff": "6 hours",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Sat, 28 Nov 2015 18:07:23 GMT"
    },
    {
        "id": "0006687",
        "summary": "© Roland Halbe \n\n\n\t\t\n      Architects: Lee H. Skolnick Architecture + Design Partnership \n\t\t\n\t\t\n      Location: Sofia, Bulgaria\n\t\t\n\t\t\n      Area: 35000.0 ft2\n\t\t\n\t\t\n      Project Year: 2015\n\t\t\n\t\t\n      Photographs: Roland Halbe \n\t\t\n\n\n    \n      \n    \n    \n      \n    \n    \n      \n ...",
        "title": "Muzeiko Children's Science Discovery Center  / Lee H. Skolnick Architecture + Design Partnership",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/irCLsKSB9xM/muzeiko-childrens-science-discovery-center-lee-h-skolnick-architecture-plus-design-partnership",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 18:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5656/727c/e58e/ce15/3300/0212/medium_jpg/RH2392-0095.jpg?1448505966",
        "diff": "6 hours",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 18:07:17 GMT"
    },
    {
        "id": "0006686",
        "summary": "Merging old and new, Cat Hill Barn in Sheffield, England, is a striking conversion of a 16th-century barn. Snook Architects successfully achieved a design where contemporary living needs are met within a timeless building in the hills of Yorkshire.&#8220;Despite a difficult ...",
        "title": "16th-Century Barn Transforms Into a Contemporary Retreat",
        "link": "http://feedproxy.google.com/~r/FreshInspirationForYourHome/~3/avmTFCLKtjQ/",
        "feed": "Freshome.com",
        "published": "Sat, 28 Nov 2015 18:00:48 GMT",
        "image": "http://cdn.freshome.com/wp-content/uploads/2015/11/architecture-design-rehabilitation.jpg",
        "diff": "6 hours",
        "websiteUrl": "http://freshome.com",
        "websiteDesc": "Freshome is a website dedicated to show you the latest trends in modern architecture, modern interior design and modern furniture design.",
        "whenLastUpdate": "Sat, 28 Nov 2015 18:06:13 GMT"
    },
    {
        "id": "0006660",
        "summary": "Kuala Lumpur-based architect and artist Jun Ong has embedded a five-storey lighting installation whithin the structure of an unfinished building in the Malaysian town of Butterworth.   (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "Kuala Lumpur-based architect and artist Jun Ong...",
        "link": "http://www.notcot.org/post/60625/",
        "feed": "NOTCOT.ORG",
        "published": "Sat, 28 Nov 2015 11:17:02 GMT",
        "image": "http://www.notempire.com/images/uploads/2-1147.jpg",
        "diff": "7 hours",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Sat, 28 Nov 2015 17:21:17 GMT"
    },
    {
        "id": "0006659",
        "summary": "the suburban home is defined by its understated material palette and operable, perforated shutters which form a seamlessly integrated façade.\nThe post concrete melbourne home by jackson clements burrows integrates perforated shutters appeared first on designboom | architecture ...",
        "title": "concrete melbourne home by jackson clements burrows integrates perforated shutters",
        "link": "http://www.designboom.com/architecture/jackson-clements-burrows-may-grove-home-melbourne-11-28-2015/",
        "feed": "designboom",
        "published": "Sat, 28 Nov 2015 17:15:18 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/jackson-clements-burrows-architects-may-grove-residence-melbourne-designboom-01-818x545.jpg",
        "diff": "7 hours",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Sat, 28 Nov 2015 17:21:09 GMT"
    },
    {
        "id": "0006658",
        "summary": "Albania Pavilion at the 2014 Venice Biennale. Image © Andrea Avezzù, Courtesy of la Biennale di Venezia\n\nSimon Battisti, Leah Whitman-Salkin, and design collective Åbäke have been selected to represent Albania at the 15th International Biennale in Venice in 2016, with their ...",
        "title": "Migration-Themed Pavilion Selected to Represent Albania at 2016 Venice Biennale",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/MwiBVA4TdHA/migration-themed-pavilion-selected-to-represent-albania-at-2016-venice-biennale",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 17:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5658/70d2/e58e/ceb2/5f00/0382/medium_jpg/Albania_(2).jpg?1448636619",
        "diff": "7 hours",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 17:07:14 GMT"
    },
    {
        "id": "0006657",
        "summary": "Taglio is located in Milan, at number 10 via Vigevano. On the ground floor of a typically Milanese block of flats with communal balconies, it is just a few feet away from the Navigli canals. The idea was to create a multifunctional space where a restaurant, a food shop, a bar ...",
        "title": "Taglio",
        "link": "http://architizer.com/projects/taglio/",
        "feed": "Architizer",
        "published": "Sat, 28 Nov 2015 17:06:17 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/46/20/4620fa3122050f22dc6d3f74ed5dc66b.jpg",
        "diff": "7 hours",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Sat, 28 Nov 2015 17:06:17 GMT"
    },
    {
        "id": "0006643",
        "summary": "Earlier this year, a plan to alter James Stirling&#39;s No.1 Poultry caused a heated discussion. Image © Flickr user merula licensed under CC BY-SA 2.0\n\nIf there’s one thing that can get the architectural community up in arms, it’s the threat of demolition being placed over a ...",
        "title": "Do Architectural Preservationists Know What They’re Fighting For?",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/NmVAB9lz2bk/do-architectural-preservationists-know-what-theyre-fighting-for",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 16:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5659/d094/e58e/ceb2/5f00/03ab/medium_jpg/1398376326_56e75307c4_b.jpg?1448726670",
        "diff": "8 hours",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 16:37:12 GMT"
    },
    {
        "id": "0006635",
        "summary": "Shift Architecture Urbanism has built a spherical cinema, a cube-shaped gallery and an elevated walkway to create a complex of design, science and technology museums in the Netherlands (+ slideshow). (more&hellip;)",
        "title": "Trio of geometric forms by Shift Architecture Urbanism form new Dutch museum complex",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/7HK86tONy-A/",
        "feed": "Dezeen",
        "published": "Sat, 28 Nov 2015 16:00:28 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Museum-Square-Limburg_Shift-architecture-urbanism_C-City_Dutch-German_Kerkrade_dezeen_sqa.jpg",
        "diff": "8 hours",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Sat, 28 Nov 2015 16:07:17 GMT"
    },
    {
        "id": "0006616",
        "summary": "London design collective WMB Studio has created a miniature modular park that monitors air quality and offers plant-covered seating for passersby (+ slideshow). (more&hellip;)",
        "title": "Portable \"parklet\" by WMB Studio adds greenery to London's streets",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/oWrpbfV34bY/",
        "feed": "Dezeen",
        "published": "Sat, 28 Nov 2015 15:00:31 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Parklet-Bench_WMBstudio_Tooley-Street_London-Bridge_Team-London-Bridge_Transport-for-London_dezeen_sqa.jpg",
        "diff": "9 hours",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Sat, 28 Nov 2015 15:07:14 GMT"
    },
    {
        "id": "0006605",
        "summary": "developed as a unique experience, the self-sufficient system is defined by its adaptable spinal structure with rooms attached as independent capsules.\nThe post gianluca santosuosso&#8217;s floating MORPhotel concept drifts with the ocean currents appeared first on designboom | ...",
        "title": "gianluca santosuosso’s floating MORPhotel concept drifts with the ocean currents",
        "link": "http://www.designboom.com/architecture/gianluca-santosuosso-morphotel-concept-11-28-2015/",
        "feed": "designboom",
        "published": "Sat, 28 Nov 2015 14:30:12 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/gianlucca-santosuosso-morphotel-floating-concept-designboom-01-818x632.jpg",
        "diff": "10 hours",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Sat, 28 Nov 2015 14:36:01 GMT"
    },
    {
        "id": "0006604",
        "summary": "I'm not sure which is funnier: the $550,000 price tag of Peter Eisenman's 40-year-old \"iconic\" House VI in Cornwall, Connecticut (it was $1.4 million two years ago); this photo that accompanies the listing...[Photo: Screenshot from New York Times listing] ...or the listing ...",
        "title": "Eisenman's House VI Marked Down",
        "link": "http://archidose.blogspot.com/2015/11/eisenmans-house-vi-marked-down.html",
        "feed": "A",
        "published": "Sat, 28 Nov 2015 14:09:00 GMT",
        "image": "http://3.bp.blogspot.com/-yb7PsJSEi3U/VlmzxPMQYCI/AAAAAAAASao/VL8MXuUxYnM/s1600/eisenman6.jpg",
        "diff": "10 hours",
        "websiteUrl": "http://archidose.blogspot.com/",
        "websiteDesc": "(Almost) daily architectural musings and imagery from New York City",
        "whenLastUpdate": "Sat, 28 Nov 2015 14:36:00 GMT"
    },
    {
        "id": "0006596",
        "summary": "White concrete is popular with architects thanks to its pure, uniform appearance, offering a less brutal alternative to board-marked and raw concrete. It is created by combining materials with lower iron, chromium and manganese levels.\nRecent examples of projects with white ...",
        "title": "Today we like: white concrete",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/iNb_IQtdPUU/",
        "feed": "Dezeen",
        "published": "Sat, 28 Nov 2015 14:00:45 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Collection-Lambert_Avignon_Berger-Berger_Laurent-Begrer-photographs_dezeen_sq1.jpg",
        "diff": "10 hours",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Sat, 28 Nov 2015 14:07:11 GMT"
    },
    {
        "id": "0006595",
        "summary": "© Robert Leš\n\n\n\t\t\n      Architects: DAR612\n\t\t\n\t\t\n      Location: Splitska, Croatia\n\t\t\n\t\t\n      Architect In Charge: Andrea Donatović Poljičak, d.i.a, Morana Lepur Donatović, d.i.a., Jakov Poljičak, d.i.a\n\t\t\n\t\t\n      Area: 300.0 sqm\n\t\t\n\t\t\n      Project Year: 2015\n\t\t\n\t\t\n      ...",
        "title": "Ana House / DAR612",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/vRBBK_BHtks/ana-house-dar612",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 14:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5656/4f05/e58e/ceb2/5f00/01e1/medium_jpg/portada_08.jpg?1448496892",
        "diff": "10 hours",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 14:07:05 GMT"
    },
    {
        "id": "0006594",
        "summary": "We have designed a new office building for the steel manufacturer Lecor. The building is situated in Kungälv, 10 kilometers north of Gothenburg. Lecor manufacture advanced steel constructions and wanted to showcase their skills in their own building. This intention in ...",
        "title": "Lecor",
        "link": "http://architizer.com/projects/lecor/",
        "feed": "Architizer",
        "published": "Sat, 28 Nov 2015 14:06:08 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/2a/f2/2af2fd4637394cd70ffd054f33e1c988.jpg",
        "diff": "10 hours",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Sat, 28 Nov 2015 14:06:08 GMT"
    },
    {
        "id": "0006586",
        "summary": "continue reading",
        "title": "An American Company Is Producing Hobbit Homes Designed To Be Covered In Grass",
        "link": "http://feedproxy.google.com/~r/contemporist/~3/OeR4REX4ex4/",
        "feed": "CONTEMPORIST",
        "published": "Sat, 28 Nov 2015 13:09:46 GMT",
        "image": "http://www.contemporist.com/wp-content/uploads/2015/11/green-homes_271115_01.jpg?1ff4a6",
        "diff": "11 hours",
        "websiteUrl": "http://www.contemporist.com",
        "websiteDesc": "Contemporary Modern Architecture Furniture Lighting Interior Design",
        "whenLastUpdate": "Sat, 28 Nov 2015 13:21:07 GMT"
    },
    {
        "id": "0006573",
        "summary": "Chilean studio DX Arquitectos has added a timber-framed roof extension to the home of a yoga teacher in Santiago, providing a studio where she can teach classes (+ slideshow). (more&hellip;)",
        "title": "DX Arquitectos extends yoga teacher's house with a blackened timber studio on top",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/P3Oj6dXwyZI/",
        "feed": "Dezeen",
        "published": "Sat, 28 Nov 2015 12:00:51 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/AYC_DX-Arquitectos_dezeen_sqa.jpg",
        "diff": "12 hours",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Sat, 28 Nov 2015 12:07:05 GMT"
    },
    {
        "id": "0006572",
        "summary": "This row house, developed by Lang Architecture in Brooklyn, N.Y., is the result of an architectural makeover. Originally a three-family residence, the home in the Carroll Gardens neighborhood now accommodates the contemporary living needs of a single family.The elegant ...",
        "title": "Italianate-Style Row House in Brooklyn Gets an Elegant Upgrade",
        "link": "http://feedproxy.google.com/~r/FreshInspirationForYourHome/~3/WkfhVSx-HA4/",
        "feed": "Freshome.com",
        "published": "Sat, 28 Nov 2015 12:00:11 GMT",
        "image": "http://cdn.freshome.com/wp-content/uploads/2015/11/architecture-contemporary-home2.jpg",
        "diff": "12 hours",
        "websiteUrl": "http://freshome.com",
        "websiteDesc": "Freshome is a website dedicated to show you the latest trends in modern architecture, modern interior design and modern furniture design.",
        "whenLastUpdate": "Sat, 28 Nov 2015 12:05:55 GMT"
    },
    {
        "id": "0006561",
        "summary": "the 'originals' and 'monochrome' collections are printed with archival inks on premium, satin-gloss paper and are available for purchase on petrolified. \nThe post iconic cars presented in sleek, minimal poster series by petrolified appeared first on designboom | architecture ...",
        "title": "iconic cars presented in sleek, minimal poster series by petrolified",
        "link": "http://www.designboom.com/art/originals-monochrome-collection-poster-series-petrolified-11-28-2015/",
        "feed": "designboom",
        "published": "Sat, 28 Nov 2015 11:15:51 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/petrolifieddesignboom01.jpg",
        "diff": "13 hours",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Sat, 28 Nov 2015 11:20:52 GMT"
    },
    {
        "id": "0006560",
        "summary": "The house program is summarized in three atmospheres which get arranged in three different stories that solve the project settlement on a site with a slope of twenty percent, this same topography foster the lyric of paths and the sequence between spaces. In direct contact with ...",
        "title": "Casa Roja",
        "link": "http://architizer.com/projects/casa-roja-2/",
        "feed": "Architizer",
        "published": "Sat, 28 Nov 2015 11:06:00 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/6e/93/6e935fc17efe1b4a7e8b9c84662d6eda.jpg",
        "diff": "13 hours",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Sat, 28 Nov 2015 11:06:00 GMT"
    },
    {
        "id": "0006552",
        "summary": "© Gareth Gardner\n\n\n\t\t\n      Architects: Studio C102\n\t\t\n\t\t\n      Location: Broadgate Cir, London EC2M 2QS, UK\n\t\t\n\t\t\n      Architect In Charge: Kyriakos Katsaros\n\t\t\n\t\t\n      Area: 8500.0 ft2\n\t\t\n\t\t\n      Project Year: 2015\n\t\t\n\t\t\n      Photographs: Gareth Gardner\n\t\t\n\n\n    \n      \n   ...",
        "title": "REBEL Gym / Studio C102",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/iGW0CI9dmns/rebel-gym-studio-c102",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 10:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5656/834d/e58e/ce15/3300/0275/medium_jpg/GARETHGARDNER-1426-HDR-C.jpg?1448510264",
        "diff": "14 hours",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 10:21:54 GMT"
    },
    {
        "id": "0006540",
        "summary": "This week on Dezeen: it was a bumper week for bridges, with Steven Holl's elevated design to span Copenhagen harbour revealed ahead of two proposals for pedestrian and cycle crossings in London. (more&hellip;)",
        "title": "This week, London and Copenhagen unveiled ambitious plans for pedestrian and cycle bridges",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/tv8W07NAsPo/",
        "feed": "Dezeen",
        "published": "Sat, 28 Nov 2015 09:00:22 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Nine-Elms-to-Pimlico-Bridge-competition_-Bystrup_Robin-Snell-Partners_-pedestrian-bicycle-bridge_River-Thames_London_dezeen_sq1.jpg",
        "diff": "15 hours",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Sat, 28 Nov 2015 09:06:56 GMT"
    },
    {
        "id": "0006530",
        "summary": "New training workshops for technical and industrial occupations: the long, horizontal building structure fits into the large-scale site, one of the former industrial district, and is in close dialogue with the verticality, which lies on the intersection skyscraper. Unchanged ...",
        "title": "Ecole des Métiers EMF",
        "link": "http://architizer.com/projects/ecole-des-metiers-emf/",
        "feed": "Architizer",
        "published": "Sat, 28 Nov 2015 08:05:51 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/e8/11/e811f75c0b9d3958d9fa9a7c1f2a5c97.jpg",
        "diff": "16 hours",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Sat, 28 Nov 2015 08:05:51 GMT"
    },
    {
        "id": "0006528",
        "summary": "located in kips bay, the nine-storey scheme consists of 55 units, varying in size from 260 to 360 square feet.\nThe post new york&#8217;s first micro-apartment building offers &#8216;all-inclusive living experience&#8217; appeared first on designboom | architecture &amp; design ...",
        "title": "new york’s first micro-apartment building offers ‘all-inclusive living experience’",
        "link": "http://www.designboom.com/architecture/carmel-place-micro-apartments-new-york-ollie-housing-model-11-28-2015/",
        "feed": "designboom",
        "published": "Sat, 28 Nov 2015 07:29:11 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/carmel-place-micro-apartments-new-york-ollie-housing-model-designboom-01-818x529.jpg",
        "diff": "17 hours",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Sat, 28 Nov 2015 07:35:41 GMT"
    },
    {
        "id": "0006524",
        "summary": "© Alberto Ferrero\n\n\n\t\t\n      Architects: Giorgio Zaetta\n\t\t\n\t\t\n      Location: Montebelluna TV, Italy\n\t\t\n\t\t\n      Area: 1000.0 sqm\n\t\t\n\t\t\n      Project Year: 2015\n\t\t\n\t\t\n      Photographs: Alberto Ferrero\n\t\t\n\n\n    \n      \n    \n    \n      \n    \n    \n      \n    \n    \n      \n    ...",
        "title": "House C / Giorgio Zaetta",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/SOBhww7yAZ0/house-c-giorgio-zaetta",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 07:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/564f/ecb1/e58e/ce7a/6900/0085/medium_jpg/001.jpg?1448078502",
        "diff": "17 hours",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 07:21:46 GMT"
    },
    {
        "id": "0006523",
        "summary": "Nanan's Antifacto Urban Lights - made in Lille, France since 2012, these are amazing headlight creatures! Predecessors to the Lampsters in #60616  (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "Nanan's Antifacto Urban Lights - made in Lille,...",
        "link": "http://www.notcot.org/post/60624/",
        "feed": "NOTCOT.ORG",
        "published": "Sat, 28 Nov 2015 00:57:01 GMT",
        "image": "http://www.notempire.com/images/uploads/lights-11.jpg",
        "diff": "17 hours",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Sat, 28 Nov 2015 07:05:47 GMT"
    },
    {
        "id": "0006516",
        "summary": "Dutch Design Week 2015: Amsterdam studio Visser &amp; Meijwaard has designed a range of colourful zip-up coffins to help make death less depressing. (more&hellip;)",
        "title": "Visser & Meijwaard designs zip-up coffins that you would \"want to be seen dead in\"",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/pSvUHH_ZQnU/",
        "feed": "Dezeen",
        "published": "Sat, 28 Nov 2015 06:00:15 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Kassiewijle_Visser_Meijwaard_dezeen_squ.jpg",
        "diff": "18 hours",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Sat, 28 Nov 2015 06:06:48 GMT"
    },
    {
        "id": "0006515",
        "summary": "Clara Hanging Flower Vase... perfect addition to take that wine bottle gift to the next level! Made of glass by Hofland.  (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "Clara Hanging Flower Vase... perfect addition...",
        "link": "http://www.notcot.org/post/60623/",
        "feed": "NOTCOT.ORG",
        "published": "Fri, 27 Nov 2015 23:57:02 GMT",
        "image": "http://www.notempire.com/images/uploads/vase-9.jpg",
        "diff": "18 hours",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Sat, 28 Nov 2015 06:05:45 GMT"
    },
    {
        "id": "0006514",
        "summary": "We love it when museums take a step forward in creativity, highlighting the design trends of the moment. The bold look of the Biesbosch Museum in Werkendam, The Netherlands, is the result of an eight-month renovation project led by Studio Marco Vermeulen.A new wing that ...",
        "title": "Dutch Museum Renovation Features Living Roof",
        "link": "http://feedproxy.google.com/~r/FreshInspirationForYourHome/~3/QW_AldmWZfQ/",
        "feed": "Freshome.com",
        "published": "Sat, 28 Nov 2015 06:00:36 GMT",
        "image": "http://cdn.freshome.com/wp-content/uploads/2015/11/architecture-modern-museum.jpg",
        "diff": "18 hours",
        "websiteUrl": "http://freshome.com",
        "websiteDesc": "Freshome is a website dedicated to show you the latest trends in modern architecture, modern interior design and modern furniture design.",
        "whenLastUpdate": "Sat, 28 Nov 2015 06:05:39 GMT"
    },
    {
        "id": "0006495",
        "summary": "© Radu Malașincu\n\n\n\t\t\n      Architects: LAMA Arhitectura\n\t\t\n\t\t\n      Location: Strada Constantin Mille 4, București, Romania\n\t\t\n\t\t\n      Area: 220.0 sqm\n\t\t\n\t\t\n      Project Year: 2015\n\t\t\n\t\t\n      Photographs: Radu Malașincu\n\t\t\n\n\n    \n      \n    \n    \n      \n    \n    \n      \n    ...",
        "title": "Control Club - Berlin Hall / LAMA Arhitectura",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/_J-suMJkvQU/control-club-berlin-hall-lama-arhitectura",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 03:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5655/2cef/e58e/ce15/3300/00fe/medium_jpg/04control.jpg?1448422616",
        "diff": "21 hours",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 03:21:35 GMT"
    },
    {
        "id": "0006494",
        "summary": "defined by a pared–down, sculptural form of concave circles, the architectural piece serves as an everyday stationery tool for the desk. \nThe post sculptural form abstracted as cantili tape dispenser by beyond object appeared first on designboom | architecture &amp; design ...",
        "title": "sculptural form abstracted as cantili tape dispenser by beyond object",
        "link": "http://www.designboom.com/design/cantili-tape-dispenser-by-beyond-object/",
        "feed": "designboom",
        "published": "Sat, 28 Nov 2015 03:15:02 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/Cantili_818-818x545.jpg",
        "diff": "21 hours",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Sat, 28 Nov 2015 03:20:30 GMT"
    },
    {
        "id": "0006493",
        "summary": "Stone & Sierra Nevada NXS IPA: A California collaboration blend of Dry-Hopped IPA and barrel aged IPA. Fantastic graphic for the collaboration!  (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "Stone & Sierra Nevada NXS IPA: A California...",
        "link": "http://www.notcot.org/post/60622/",
        "feed": "NOTCOT.ORG",
        "published": "Fri, 27 Nov 2015 21:02:02 GMT",
        "image": "http://www.notempire.com/images/uploads/NXS.jpg",
        "diff": "21 hours",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Sat, 28 Nov 2015 03:05:37 GMT"
    },
    {
        "id": "0006487",
        "summary": "TABLE SET: Olive Oil, Salt and Pepper. Designed by Peleg with Shahar Nissim, HIT  (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "TABLE SET: Olive Oil, Salt and Pepper. Designed...",
        "link": "http://www.notcot.org/post/60621/",
        "feed": "NOTCOT.ORG",
        "published": "Fri, 27 Nov 2015 20:02:01 GMT",
        "image": "http://www.notempire.com/images/uploads/tableset3.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Sat, 28 Nov 2015 02:05:34 GMT"
    },
    {
        "id": "0006481",
        "summary": "Playable ART Balance - wooden puzzle/toy/desk object!  (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "Playable ART Balance - wooden puzzle/toy/desk...",
        "link": "http://www.notcot.org/post/60620/",
        "feed": "NOTCOT.ORG",
        "published": "Fri, 27 Nov 2015 19:02:01 GMT",
        "image": "http://www.notempire.com/images/uploads/uzzle.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Sat, 28 Nov 2015 01:05:32 GMT"
    },
    {
        "id": "0006476",
        "summary": "panasonic&#8217;s minimal washing machine collects 2015 g-mark japan GOOD DESIGN best 100 awardall images courtesy of panasonic &#160; &#160; &#160; &#160; focusing on interior design harmony, panasonic elevates the laundry experience with a front loading washing machine ...",
        "title": "panasonic’s minimal washing machine collects 2015 g-mark japan GOOD DESIGN best 100 award",
        "link": "http://www.designboom.com/technology/panasonics-washing-machine-2015-g-mark-japan-good-design-best-100-11-28-2015/",
        "feed": "designboom",
        "published": "Sat, 28 Nov 2015 00:30:16 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/panasonic-front-load-washing-machine-g-mark-japan-good-design-2015-designboom-01-818x477.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Sat, 28 Nov 2015 00:35:23 GMT"
    },
    {
        "id": "0006474",
        "summary": "© Peter Molick Photography\n\n\n\t\t\n      Architects: Derrington Building Studio\n\t\t\n\t\t\n      Location: Austin, TX, USA\n\t\t\n\t\t\n      Architect In Charge: Heath Henderson\n\t\t\n\t\t\n      Area: 3432.0 ft2\n\t\t\n\t\t\n      Project Year: 2015\n\t\t\n\t\t\n      Photographs: Peter Molick Photography\n\t\t\n\n\n ...",
        "title": "Khabele Elementary Expansion / Derrington Building Studio",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/hcq-4J_ZcV8/khabele-elementary-expansion-derrington-building-studio",
        "feed": "ArchDaily",
        "published": "Sat, 28 Nov 2015 00:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5650/f05b/e58e/ce7a/6900/00c3/medium_jpg/KBEX_021_v1.jpg?1448144971",
        "diff": "a day",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Sat, 28 Nov 2015 00:06:27 GMT"
    },
    {
        "id": "0006469",
        "summary": "Adventure 16: 52 Hikes, A Hike-A-Week In A Jar Kit! A DIY Kit for LA and San Diego Counties in store.  (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "Adventure 16: 52 Hikes, A Hike-A-Week In A Jar...",
        "link": "http://www.notcot.org/post/60619/",
        "feed": "NOTCOT.ORG",
        "published": "Fri, 27 Nov 2015 17:15:02 GMT",
        "image": "http://www.notempire.com/images/uploads/hike-2.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Fri, 27 Nov 2015 23:20:27 GMT"
    },
    {
        "id": "0006459",
        "summary": "© Javier Orive\n\n\n\t\t\n      Architects: Rosana Caro Martínez\n\t\t\n\t\t\n      Location: 41013 Seville, Sevilla, Spain\n\t\t\n\t\t\n      Area: 1390.0 sqm\n\t\t\n\t\t\n      Project Year: 2011\n\t\t\n\t\t\n      Photographs: Javier Orive\n\t\t\n\n\n    \n      \n    \n    \n      \n    \n    \n      \n    \n    \n      \n   ...",
        "title": "Renovation of Sports Pavillion at University Campus / Rosana Caro Martínez",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/XiPUuhdPai8/renovation-of-sports-pavillion-at-university-campus-rosana-caro-martinez",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 22:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/564d/2e38/e58e/ce8c/4200/027c/medium_jpg/PORTADA_archdaily-rcm-ext_03.jpg?1447898664",
        "diff": "a day",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 22:21:23 GMT"
    },
    {
        "id": "0006451",
        "summary": "This remodel of a 1970s Joseph Eichler house in Palo Alto, Calif., completed by San Francisco-based Yamamar Design, displays a modern personality sprinkled with personal touches.&#8220;The project took focus as a result of the collaboration between architect, interior decorator ...",
        "title": "California Eichler House Remodel Features Wide-Open Spaces",
        "link": "http://feedproxy.google.com/~r/FreshInspirationForYourHome/~3/cNbquljblWQ/",
        "feed": "Freshome.com",
        "published": "Fri, 27 Nov 2015 22:00:05 GMT",
        "image": "http://cdn.freshome.com/wp-content/uploads/2015/11/architecture-modern-house-design.jpg",
        "diff": "a day",
        "websiteUrl": "http://freshome.com",
        "websiteDesc": "Freshome is a website dedicated to show you the latest trends in modern architecture, modern interior design and modern furniture design.",
        "whenLastUpdate": "Fri, 27 Nov 2015 22:05:18 GMT"
    },
    {
        "id": "0006444",
        "summary": "mana contemporary presents the 'untitled' art car at the wynwood convention center during miami art week 2015.\nThe post os gemeos turn volkswagen beetle into a figure filled with colorful curiosities appeared first on designboom | architecture &amp; design magazine.",
        "title": "os gemeos turn volkswagen beetle into a figure filled with colorful curiosities",
        "link": "http://www.designboom.com/art/os-gemeos-mana-contemporary-art-miami-2015-tiroche-deleon-collection-wooden-car-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 21:30:19 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/os-gemeos-mana-contemporary-art-miami-2015-tiroche-deleon-collection-designboom-06.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 21:35:15 GMT"
    },
    {
        "id": "0006439",
        "summary": "One of BIG's most high-profile projects under construction, the Amager Bakke waste-to-power plant in Copenhagen, will have quite the party trick up its sleeve. In order to give locals a new understanding of the issue of global warming, for every tonne of CO2 generated by the ...",
        "title": "AD Interviews: BIG's Jakob Lange / Chicago Architecture Biennial",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/Bd_hNV_yevc/ad-interviews-bigs-jakob-lange-chicago-architecture-biennial",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 21:00:00 GMT",
        "image": "http://feeds.feedburner.com/~r/ArchDaily/~4/Bd_hNV_yevc",
        "diff": "a day",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 21:21:20 GMT"
    },
    {
        "id": "0006438",
        "summary": "German studio KSP Jürgen Engel Architekten's glass-covered design for the Shenzhen Art Museum and Library complex in China beat proposals from a number of star architects. (more&hellip;)",
        "title": "KSP Jürgen Engel Architekten wins competition to design Shenzhen Art Museum and Library",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/izQkL5NJ1vE/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 21:00:24 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Shenzhen-Art-Museum-Library_KSP-Jurgen-Engel-Architekten_dezeen_sqa.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 21:06:25 GMT"
    },
    {
        "id": "0006427",
        "summary": "Courtesy of gmp Architekten\n\nFollowing a closed competition, which included practices like OMA, KPF and Henn Architects, gmp Architects was selected to design the new CNPEC Headquarters in Longgang, Shenzhen, Southeast China. The power corporation called for a new building that ...",
        "title": "gmp Designs New Headquarters for CNPEC in Shenzhen, China",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/x1LNg4I83Ow/cnpec-headquarters-privileges-employee-health-in-winning-proposal-by-gmp-architects",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 19:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5655/eec4/e58e/ce15/3300/016f/medium_jpg/3170_150522_Bird_Day_1.jpg?1448472239",
        "diff": "a day",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 20:21:18 GMT"
    },
    {
        "id": "0006415",
        "summary": "Our US job of the week on Dezeen Jobs is for an architect/designer at Abramson Teiger in California, whose Kelly Residence in Culver City is pictured. Visit the ad for full details or browse other architecture and design opportunities on Dezeen Jobs.",
        "title": "US job of the week: architect/designer at Abramson Teiger",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/MDvhUDHOkqE/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 19:51:42 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/US-JOTW-Abramson-Teiger-for-Dezeen.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 20:06:22 GMT"
    },
    {
        "id": "0006381",
        "summary": "Hofland Pots/Planters! Loving the Sunrise Pots, Bumble Pots, Tula Pots, and Plume Vase.   (Want more? See NOTCOT.org and NOTCOT.com)",
        "title": "Hofland Pots/Planters! Loving the Sunrise Pots,...",
        "link": "http://www.notcot.org/post/60618/",
        "feed": "NOTCOT.ORG",
        "published": "Fri, 27 Nov 2015 02:55:15 GMT",
        "image": "http://www.notempire.com/images/uploads/flower-13.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.notcot.org/",
        "websiteDesc": "For YOUR ideas + aesthetics + amusement.",
        "whenLastUpdate": "Fri, 27 Nov 2015 19:05:49 GMT"
    },
    {
        "id": "0006367",
        "summary": "Movie: American designer Marc Thorpe reveals which vegetable influenced his Husk chair for Moroso in our next exclusive movie for the Italian furniture brand. (more&hellip;)",
        "title": "Marc Thorpe's latest chair for Moroso is based on the shapes of corn husks",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/1LWre5AtvM0/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 18:42:00 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Husk-Marc-Thorpe-Moroso_Dezeen_02.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 18:51:19 GMT"
    },
    {
        "id": "0006366",
        "summary": "Courtesy of Marco Gárate N.\n\n\n\t\t\n      Architects: Arq2g arquitectura\n\t\t\n\t\t\n      Location: Las Monjas, Valparaíso, Valparaíso, Región de Valparaíso, Chile\n\t\t\n\t\t\n      Architect In Charge: Marco Gárate Navarrete\n\t\t\n\t\t\n      Area: 50.0 sqm\n\t\t\n\t\t\n      Project Year: 2013\n\t\t\n\t\t\n    ...",
        "title": "Suarez House / Arq2g arquitectura",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/kpTi-Iri-LY/suarez-house-arq2g-arquitectura",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 18:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5653/bb23/e58e/ce15/3300/004b/medium_jpg/03_VIV_SUAREZ.jpg?1448327956",
        "diff": "a day",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 18:21:13 GMT"
    },
    {
        "id": "0006365",
        "summary": "Art is a great gift that not everyone thinks to buy for themselves. Not only will it add life to a living space, it will remind the recipient of the person that gifted it to them. Here, we round up some art at various price points that your friends and family would most likely ...",
        "title": "2015 Gift Guide: Art Lovers",
        "link": "http://feedproxy.google.com/~r/design-milk/~3/wlUTy5D_aIc/",
        "feed": "Design",
        "published": "Fri, 27 Nov 2015 18:00:08 GMT",
        "image": "http://2.design-milk.com/images/2015/11/dm_giftguide_ARTLOVERS-2015-600x800.jpg",
        "diff": "a day",
        "websiteUrl": "http://design-milk.com",
        "websiteDesc": "Dedicated to modern design",
        "whenLastUpdate": "Fri, 27 Nov 2015 18:20:12 GMT"
    },
    {
        "id": "0006364",
        "summary": "made from steel, aluminum and maple, the wireless ’steel speaker’ utilizes an omnidirectional design layout and will come in either raw steel or graphite finish.\nThe post steel, aluminum and wood converge in joey roth’s wireless speakers appeared first on designboom | ...",
        "title": "steel, aluminum and wood converge in joey roth’s wireless speakers",
        "link": "http://www.designboom.com/technology/joey-roth-steel-speaker-wireless-speaker-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 18:15:41 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/joey-roth-steel-speaker-designboom-01-818x557.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 18:20:08 GMT"
    },
    {
        "id": "0006328",
        "summary": "Business news: San Francisco studio Wood Thumb is opposing Black Friday's discounting frenzy by upping the price of its products, adding a \"Maker's Bonus\" for its craftspeople. (more&hellip;)",
        "title": "Design company raises prices on Black Friday in support of craftspeople",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/jwFtFRCcCis/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 17:14:08 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Wood-Thumb-raises-prices-Black-Friday_dezeen_936_3.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 17:21:15 GMT"
    },
    {
        "id": "0006327",
        "summary": "In the Melbourne suburb of Caulfield, the Cumquat Tree House is a design project undertaken by Christopher Megowan Design, who renovated the original Art Deco house to create a central spine that framed a view of an existing cumquat tree in the backyard. Along with the ...",
        "title": "A Renovation & Extension Upgrades an Art Deco House",
        "link": "http://feedproxy.google.com/~r/design-milk/~3/A7BTC8cRQ6Y/",
        "feed": "Design",
        "published": "Fri, 27 Nov 2015 17:00:15 GMT",
        "image": "http://3.design-milk.com/images/2015/11/Cumquat-Tree-House-Christopher-Megowan-1-600x559.jpg",
        "diff": "a day",
        "websiteUrl": "http://design-milk.com",
        "websiteDesc": "Dedicated to modern design",
        "whenLastUpdate": "Fri, 27 Nov 2015 17:20:09 GMT"
    },
    {
        "id": "0006293",
        "summary": "The last chair designed by late Danish cabinetmaker Frits Henningsen has been put back into production by furniture company Carl Hansen &amp; Søn. (more&hellip;)",
        "title": "Frits Henningsen's Signature Chair rereleased by Carl Hansen & Søn",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/5KV9q6Euras/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 16:26:27 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/The-Signature-Chair_Frits-Henningsen_Carl-Hansen-Son_dezeen_sq.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 16:36:13 GMT"
    },
    {
        "id": "0006292",
        "summary": "© Cameron Blaylock\n\n\n\t\t\n      Architects: Architensions\n\t\t\n\t\t\n      Location: Brooklyn, NY 11222, USA\n\t\t\n\t\t\n      Architects In Charge: Alessandro Orsini, Nick Roseboro\n\t\t\n\t\t\n      Project Year: 2015\n\t\t\n\t\t\n      Photographs: Cameron Blaylock\n\t\t\n\n\n    \n      \n    \n    \n      \n    ...",
        "title": "Writing Pavilion / Architensions",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/88nzFgcp3Vg/writing-pavilion-architensions",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 16:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5656/6e2c/e58e/ce15/3300/01f9/medium_jpg/ARCHITENSIONS-WRITINGPAVILION-11.jpg?1448504860",
        "diff": "a day",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 16:21:07 GMT"
    },
    {
        "id": "0006276",
        "summary": "AXF’s residential development, Imperial Doncaster, was recently completed, delivering the ultimate in luxury, comfort and convenience in one of Melbourne’s most rapidly changing suburbs. The multi-unit residential development is set on a steeply sloping site off Williamsons Road ...",
        "title": "Imperial Doncaster",
        "link": "http://architizer.com/projects/imperial-doncaster/",
        "feed": "Architizer",
        "published": "Fri, 27 Nov 2015 16:05:10 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/de/70/de70ed9fa41d6db9a666b85c361130fe.jpg",
        "diff": "a day",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Fri, 27 Nov 2015 16:05:10 GMT"
    },
    {
        "id": "0006275",
        "summary": "Our sister shop Adorn Milk is having a special holiday free shipping sale! Shop now! Here are some collections we put together to help you find the right gift:  Necklaces Under $100  Earrings Under $75   Jewelry Under $50  For Him  Modern Cufflinks",
        "title": "Adorn Milk Holiday Sale",
        "link": "http://feedproxy.google.com/~r/design-milk/~3/NeqqqehQqL0/",
        "feed": "Design",
        "published": "Fri, 27 Nov 2015 16:00:33 GMT",
        "image": "http://2.design-milk.com/images/2015/11/adornmilk_siteimages_cybermon_SQUARE-1-600x600.jpg",
        "diff": "a day",
        "websiteUrl": "http://design-milk.com",
        "websiteDesc": "Dedicated to modern design",
        "whenLastUpdate": "Fri, 27 Nov 2015 16:05:05 GMT"
    },
    {
        "id": "0006257",
        "summary": "MAISON&amp;OBJET Paris, Stockholm Furniture Fair and Fiera Milano represent some of the top furniture, accessory and lighting fairs in Europe. The best contemporary designs are introduced during these fairs, and lighting designers didn’t disappoint this year. Here are 10 of the ...",
        "title": "10 of the Most Stunning New Light Fixtures",
        "link": "http://feedproxy.google.com/~r/FreshInspirationForYourHome/~3/_R8ffUk1EXQ/",
        "feed": "Freshome.com",
        "published": "Fri, 27 Nov 2015 14:00:59 GMT",
        "image": "http://cdn.freshome.com/wp-content/uploads/2015/11/bocci-73.jpg",
        "diff": "a day",
        "websiteUrl": "http://freshome.com",
        "websiteDesc": "Freshome is a website dedicated to show you the latest trends in modern architecture, modern interior design and modern furniture design.",
        "whenLastUpdate": "Fri, 27 Nov 2015 15:50:02 GMT"
    },
    {
        "id": "0006256",
        "summary": "the show contains objects that range from rainbows, to tables, to spaceships, to blocks, that reference the idea of the mutation of functions. \nThe post carwan gallery presents karen chekerdjian&#8217;s first solo exhibition in the US appeared first on designboom | architecture ...",
        "title": "carwan gallery presents karen chekerdjian’s first solo exhibition in the US",
        "link": "http://www.designboom.com/design/carwan-gallery-presents-karen-chekerdjian-design-miami-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 15:30:40 GMT",
        "image": "http://www.designboom.com/wp-content/dbsub/390225/2015-11-26/img_1_1448554034_3e26a6594e4a0615e81b2a3391df87c8.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 15:49:59 GMT"
    },
    {
        "id": "0006255",
        "summary": "This \"floating\" art and literary museum by American studio OLI Architecture is housed in a grouping of textured concrete blocks, which are elevated over a lake in China's Zhejiang Province (+ slideshow). (more&hellip;)",
        "title": "Mu Xin Art Museum by OLI Architecture sits over a lake in eastern China",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/e76LgeMgeeY/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 15:07:03 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Mu-Xin-Art-Museum_OLI-Architecture_dezeen_sqa.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 15:21:10 GMT"
    },
    {
        "id": "0006254",
        "summary": "Danish designer Marie Hesseldahl makes it easy to get light where you need it with the SNAP LAMP. The lamp offers a flexible lighting solution with its clamp base that lets you attach it to any surface that ranges from 8-40mm thick. Its simple shape reflects her Scandinavian ...",
        "title": "A Lamp That Easily Snaps into Place Wherever You Need It",
        "link": "http://feedproxy.google.com/~r/design-milk/~3/JSXHz64fV4o/",
        "feed": "Design",
        "published": "Fri, 27 Nov 2015 15:00:55 GMT",
        "image": "http://3.design-milk.com/images/2015/11/Marie-Hesseldahl-SNAP-LAMP-1-600x479.jpg",
        "diff": "a day",
        "websiteUrl": "http://design-milk.com",
        "websiteDesc": "Dedicated to modern design",
        "whenLastUpdate": "Fri, 27 Nov 2015 15:20:04 GMT"
    },
    {
        "id": "0006243",
        "summary": "A 100 year old school-building in the center of Amsterdam is transformed into 10 spacious and sustainable apartments directly for the group Ons Dorp Amsterdam (Our Village Amsterdam) of 10 young families. Each apartment has a different floor plan and different materials based on ...",
        "title": "Ons Dorp Old School Conversion",
        "link": "http://architizer.com/projects/ons-dorp-amsterdam/",
        "feed": "Architizer",
        "published": "Fri, 27 Nov 2015 15:05:07 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/1f/0f/1f0fbadc5f2203117e7387c0327839cf.jpg",
        "diff": "a day",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Fri, 27 Nov 2015 15:05:07 GMT"
    },
    {
        "id": "0006242",
        "summary": "DrDerm Dermatology Clinic, by Atelier Central Arquitectos, was completed with the help of DIMSCALE&#39;s cost management. Image © Fernando Guerra | FG+SG\n\nTo talk about architecture and construction without ever mentioning cost overruns is not an easy thing to do. These kind of ...",
        "title": "Why Cost Management Works Better when Architects Are in Charge",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/sftdV8sr654/why-cost-management-works-better-when-architects-are-in-charge",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 14:30:00 GMT",
        "image": "http://images.adsttc.com/media/images/5657/4f7a/e58e/ceb2/5f00/02eb/medium_jpg/99.jpg?1448562536",
        "diff": "a day",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 14:51:03 GMT"
    },
    {
        "id": "0006226",
        "summary": "© Raphael Bourelly\n\n\n\t\t\n      Architects: Nathanael Dorent, Mark Havasi\n\t\t\n\t\t\n      Location: Biéville-Beuville, France\n\t\t\n\t\t\n      Area: 149.0 sqm\n\t\t\n\t\t\n      Project Year: 2015\n\t\t\n\t\t\n      Photographs: Raphael Bourelly\n\t\t\n\n\n    \n      \n    \n    \n      \n    \n    \n      \n    \n   ...",
        "title": "Maison Spirale  / Nathanael Dorent + Mark Havasi",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/KT5_LwlpjTg/maison-spirale-nathanael-dorent-plus-mark-havasi",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 14:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5656/4a09/e58e/ce15/3300/01c2/medium_jpg/portada_ML_03_VUE_DE_LA_RUE_3_%C2%A9Raphael_Bourelly.jpg?1448495607",
        "diff": "a day",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 14:21:02 GMT"
    },
    {
        "id": "0006225",
        "summary": "The ever-popular and always growing Poppin continues its way converting one boring office at a time into inspiring workspaces. With four years already under his hat, Senior Design Manager Matteo Bonacina has worked closely with Jeff Miller and the team to create the recently ...",
        "title": "Friday Five with Matteo Bonacina of Poppin",
        "link": "http://feedproxy.google.com/~r/design-milk/~3/FXORmBqewzY/",
        "feed": "Design",
        "published": "Fri, 27 Nov 2015 14:00:54 GMT",
        "image": "http://3.design-milk.com/images/2015/11/F5-Matteo-Bonacina-0-Headshot-600x480.jpg",
        "diff": "a day",
        "websiteUrl": "http://design-milk.com",
        "websiteDesc": "Dedicated to modern design",
        "whenLastUpdate": "Fri, 27 Nov 2015 14:20:01 GMT"
    },
    {
        "id": "0006210",
        "summary": "Few holidays epitomize consumerism, commodity, and questionable ethics like Black Friday. Observed around the world, including places like India, France, Mexico, and the United States, the day has become synonymous with shopping, discounts, and significant safety risks. Getting ...",
        "title": "Priceless: The Fashionable Architecture of Black Friday",
        "link": "http://architizer.com/blog/black-friday/",
        "feed": "Architizer",
        "published": "Fri, 27 Nov 2015 14:05:05 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/b5/19/b51956bc5c182e97f79f30c8933ee2a2.jpg",
        "diff": "a day",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Fri, 27 Nov 2015 14:05:05 GMT"
    },
    {
        "id": "0006196",
        "summary": "Hiroshi Nakamura, architect of the Ribbon Chapel in Japan, describes the design ideology and his personal favorite elements of the project in this stunning new video by Matthew Allard ACS. Shooting the chapel at various times during the day, its changing characteristics are ...",
        "title": "Hiroshi Nakamura Describes the Inspiration Behind the Ribbon Chapel in This Stunning Video",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/SaZassvtbNs/hiroshi-nakamura-describes-the-design-ideology-behind-the-ribbon-chapel-in-this-stunning-video",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 13:00:00 GMT",
        "image": "http://feeds.feedburner.com/~r/ArchDaily/~4/SaZassvtbNs",
        "diff": "a day",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 13:20:59 GMT"
    },
    {
        "id": "0006190",
        "summary": "Some of the items discounted on Black Friday (clockwise from top left): The Present Clock, part of the MoMA Store 20% off sale; the Eames Lounge chair, part of the Y Living Herman Miller sale; the Tolomeo Lamp, part of the Lightology 20% off sale; the Unikko Duvet, part of the ...",
        "title": "Black Friday 2015 Deals: Sales on Furniture, Decor, and More",
        "link": "http://curbed.com/archives/2015/11/27/black-friday-2015-black-friday-sale-black-friday-deal-furniture-decor.php",
        "feed": "Curbed",
        "published": "Fri, 27 Nov 2015 11:51:56 GMT",
        "image": "http://curbed.com/uploads/black%20friday-thumb.jpg",
        "diff": "a day",
        "websiteUrl": "http://curbed.com/",
        "websiteDesc": "Interior Design, Decor, and Real Estate",
        "whenLastUpdate": "Fri, 27 Nov 2015 13:06:44 GMT"
    },
    {
        "id": "0006182",
        "summary": "The facade of this computer research centre at Hungary's University of Debrecen has been designed to reflect its function, with a grooved pattern inspired by a circuitboard (+ slideshow). (more&hellip;)",
        "title": "NAPUR Architect creates circuitboard pattern on facade of Super Computer Centre",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/Q2jlIu6hNqg/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 12:26:01 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Super-Computer-Centre_Napur_dezeen_936_0.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 12:36:02 GMT"
    },
    {
        "id": "0006181",
        "summary": "the project was realized during a year of research and development, and combines traditional crafts with advanced technologies. \nThe post ronan + erwan bouroullec install 17 screens inside tel aviv&#8217;s museum of art appeared first on designboom | architecture &amp; design ...",
        "title": "ronan + erwan bouroullec install 17 screens inside tel aviv’s museum of art",
        "link": "http://www.designboom.com/design/ronan-erwan-bouroullec-brothers-17-screens-exhibition-tel-aviv-museum-of-art-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 12:23:55 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/ronan-erwan-bouroullec-brothers-17-screens-exhibition-tel-aviv-museum-of-art-designboom-01-818x545.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 12:34:51 GMT"
    },
    {
        "id": "0006171",
        "summary": "for proteca's 10th anniversary, the japanese designer has been involved with the creation of a new shell suitcase, the design of the flagship store, and the company's refreshed identity.\nThe post nendo re-brands proteca with new products and tokyo flagship store appeared first ...",
        "title": "nendo re-brands proteca with new products and tokyo flagship store",
        "link": "http://www.designboom.com/design/nendo-proteca-10th-anniversary-flagship-360-suitcase-rebranding-tokyo-japan-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 12:06:32 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/nendo_proteca_designboom_002.jpg",
        "diff": "a day",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 12:19:50 GMT"
    },
    {
        "id": "0006170",
        "summary": "CS is short for Colinas del Sol; the name of the street where we find a series of houses with similar dimensions, facades and back patios as the main source of light and ventilation. Our intervention in the neighborhood consists of two houses projected for a plot with 22 m in ...",
        "title": "CS HOUSES",
        "link": "http://architizer.com/projects/cs-houses/",
        "feed": "Architizer",
        "published": "Fri, 27 Nov 2015 12:04:59 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/86/4d/864d7e276f97b7da66798715e010dab5.jpg",
        "diff": "2 days",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Fri, 27 Nov 2015 12:04:59 GMT"
    },
    {
        "id": "0006164",
        "summary": "Our job of the week on Dezeen Jobs is for an interior architect at Jump Studios, which recently renovated a 19th-century battery factory in Madrid to create the sixth Google campus (pictured). Visit the ad for full details or browse other architecture and design opportunities on ...",
        "title": "Job of the week: interior architect at Jump Studios",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/7ui-Stnx0qc/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 11:49:25 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/JOTW-Jump-Studios.jpg",
        "diff": "2 days",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 11:51:00 GMT"
    },
    {
        "id": "0006163",
        "summary": "continue reading",
        "title": "16 Gift Ideas For Those Who Love Little Gardens",
        "link": "http://feedproxy.google.com/~r/contemporist/~3/YhkTjIPQFuM/",
        "feed": "CONTEMPORIST",
        "published": "Fri, 27 Nov 2015 11:39:23 GMT",
        "image": "http://www.contemporist.com/wp-content/uploads/2015/11/garden-gifts_271115_01.jpg?1ff4a6",
        "diff": "2 days",
        "websiteUrl": "http://www.contemporist.com",
        "websiteDesc": "Contemporary Modern Architecture Furniture Lighting Interior Design",
        "whenLastUpdate": "Fri, 27 Nov 2015 11:49:58 GMT"
    },
    {
        "id": "0006160",
        "summary": "the protruding concrete brutalist structures and its bleak atmospheres are primary elements in the artist's work.\nThe post pouria khojastehpays imagines apocalyptic landscapes appeared first on designboom | architecture &amp; design magazine.",
        "title": "pouria khojastehpays imagines apocalyptic landscapes",
        "link": "http://www.designboom.com/art/pouria-khojastehpays-kadingirra-apocalypctic-landscapes-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 11:30:04 GMT",
        "image": "http://www.designboom.com/wp-content/dbsub/398213/2015-11-26/img_1_1448574229_648249591ee2e97dbb79fa806b783cd2.jpg",
        "diff": "2 days",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 11:34:48 GMT"
    },
    {
        "id": "0006158",
        "summary": "Courtesy of Mecanoo\n\nMecanoo has released their proposal for the Longhua Art Museum and Library, designed in collaboration with HS Architects. The proposal was a finalist for a competition to design a new cultural center in Baoan Qu, a district of Shenzhen, China. Their design ...",
        "title": "Tradition and Modernity Come Together in Mecanoo and HS Architects’ Proposal for the Longhua Art Museum and Library",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/ko6qKfOo04E/tradition-and-modernity-come-together-in-mecanoo-and-hs-architects-longhua-art-museum-and-library-in-china",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 11:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5655/154c/e58e/ce15/3300/00f7/medium_jpg/Longhua_Art_Museum_and_Library_Entrance.jpg?1448416574",
        "diff": "2 days",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 11:20:54 GMT"
    },
    {
        "id": "0006153",
        "summary": "Taking their cue from nature, exoskeleton buildings challenge the mantra that ‘less is more’ when it comes to celebrating our cities. Bold and unflinching, these structures are finely tuned exponents of the dialogue that exists between architect and engineer. The coming together ...",
        "title": "Full Exposure: 7 Exoskeleton Structures Achieve New Feats of Engineering",
        "link": "http://architizer.com/blog/exoskeleton-1/",
        "feed": "Architizer",
        "published": "Fri, 27 Nov 2015 11:04:56 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/25/f5/25f56569c190995b107ea8ebb6a4ff5d.jpg",
        "diff": "2 days",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Fri, 27 Nov 2015 11:04:56 GMT"
    },
    {
        "id": "0006152",
        "summary": "the project demonstrates how a structure of folded paper pieces can tap into the fundamental properties of light to produce a photograph. \nThe post kelli anderson cuts and folds paper into pop-up book pin hole camera appeared first on designboom | architecture &amp; design ...",
        "title": "kelli anderson cuts and folds paper into pop-up book pin hole camera",
        "link": "http://www.designboom.com/design/kelli-anderson-this-book-is-a-camera-pin-hole-camera-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 11:00:32 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/kelli-anderson-this-book-is-a-camera-pin-hole-camera-designboom-01-818x545.jpg",
        "diff": "2 days",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 11:04:47 GMT"
    },
    {
        "id": "0006151",
        "summary": "Reindeer, peacocks and foxes adorn these Christmas stamps designed by Studio Tord Boontje for Dutch national delivery company PostNL. (more&hellip;)",
        "title": "Tord Boontje's festive stamps feature \"small stories\" of animals and people",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/yUKzmHkTouk/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 10:28:26 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Christmas-stamps_Studio-Tord-Boontje_Netherlands_dezeen_sq.jpg",
        "diff": "2 days",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 10:50:58 GMT"
    },
    {
        "id": "0006146",
        "summary": "the solo exhibition presents the transition between two of the dutch artist's key projects: 'neo-futurism' and recent works from the 'new tribal labyrinth' series.\nThe post neo-futurism and tribal labyrinths fill joep van lieshout&#8217;s primitive modern world appeared first on ...",
        "title": "neo-futurism and tribal labyrinths fill joep van lieshout’s primitive modern world",
        "link": "http://www.designboom.com/art/joep-van-lieshout-primitive-modern-at-almine-rech-gallery-brussels-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 10:29:52 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/joep-van-lieshout-almine-rech-gallery-brussels-primitive-modern-designboom-01.jpg",
        "diff": "2 days",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 10:34:45 GMT"
    },
    {
        "id": "0006145",
        "summary": "© Stephane Chalmeau\n\n\n\t\t\n      Architects: Atelier Phileas\n\t\t\n\t\t\n      Location: 19 Rue de Presles, 93300 Aubervilliers, France\n\t\t\n\t\t\n      Project Manager : Marie-Sophie Rollet\n\t\t\n\t\t\n      Area: 5600.0 sqm\n\t\t\n\t\t\n      Project Year: 2013\n\t\t\n\t\t\n      Photographs: Stephane ...",
        "title": "Multi-Purpose Education Centre / Atelier Phileas",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/0YhhrefFbZE/multi-purpose-education-centre-atelier-phileas",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 10:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5656/7aab/e58e/ceb2/5f00/0242/medium_jpg/CF051264R%E2%88%8FS_copy.jpg?1448508067",
        "diff": "2 days",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 10:20:51 GMT"
    },
    {
        "id": "0006138",
        "summary": "Bartolo Villemard's approach stems from a social humanist involvement which outlines possible contexts relative to modes, program and use. Notions of use, comfort and domesticity are in fact the foundation of a series of studies that guides the agency to deliver quality housing ...",
        "title": "Winter Gardens",
        "link": "http://architizer.com/projects/winter-gardens/",
        "feed": "Architizer",
        "published": "Fri, 27 Nov 2015 10:04:54 GMT",
        "image": "https://acdn.architizer.com/thumbnails-PRODUCTION/99/78/9978cbf9e87c692e286159fe1e05c9f9.jpg",
        "diff": "2 days",
        "websiteUrl": "http://architizer.com/",
        "websiteDesc": "Latest posts from the Architizer Blog",
        "whenLastUpdate": "Fri, 27 Nov 2015 10:04:54 GMT"
    },
    {
        "id": "0006137",
        "summary": "the scheme is part of a large cultural masterplan for budapest that involves the construction of five new museum buildings.\nThe post SANAA selected ahead of snøhetta to build new national gallery of hungary appeared first on designboom | architecture &amp; design magazine.",
        "title": "SANAA selected ahead of snøhetta to build new national gallery of hungary",
        "link": "http://www.designboom.com/architecture/sanaa-budapest-the-new-national-gallery-of-hungary-museum-liget-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 09:59:04 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/SANAA-budapest-the-new-national-gallery-of-hungary-museum-liget-designboom-02.jpg",
        "diff": "2 days",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 10:04:44 GMT"
    },
    {
        "id": "0006132",
        "summary": "he layered locked grooved records and surrounded the turntable with -  audio triggers connected to analogue synthesizers, mechanically played percussions and a triggered drum machine.\nThe post watch artist graham dunning hack a turntable to produce electronic dance track ...",
        "title": "watch artist graham dunning hack a turntable to produce electronic dance track",
        "link": "http://www.designboom.com/technology/graham-dunning-mechanical-techno-turntable-project-11-27-2015/",
        "feed": "designboom",
        "published": "Fri, 27 Nov 2015 09:30:20 GMT",
        "image": "http://www.designboom.com/wp-content/uploads/2015/11/graham-dunning-mechanical-techno-project-designboom-01-818x460.jpg",
        "diff": "2 days",
        "websiteUrl": "http://www.designboom.com",
        "websiteDesc": "designboom magazine | your first source for architecture, design & art news",
        "whenLastUpdate": "Fri, 27 Nov 2015 09:34:42 GMT"
    },
    {
        "id": "0006113",
        "summary": "Chilean architect Felipe Assadi has built a series of wooden hotel cabins on a Chilean hillside, offering guests the chance to glimpse wild llamas, pumas and rheas in their natural habitat (+ slideshow). (more&hellip;)",
        "title": "Timber cabins provide guest suites for Patagonia's remote Awasi Hotel",
        "link": "http://feedproxy.google.com/~r/dezeen/~3/NUPy0RUIkCg/",
        "feed": "Dezeen",
        "published": "Fri, 27 Nov 2015 08:00:40 GMT",
        "image": "http://static.dezeen.com/uploads/2015/11/Awasi-Hotel_Felipe-Assadi_dezeen_936_sq.jpg",
        "diff": "2 days",
        "websiteUrl": "http://www.dezeen.com",
        "websiteDesc": "architecture and design magazine",
        "whenLastUpdate": "Fri, 27 Nov 2015 08:05:50 GMT"
    },
    {
        "id": "0006112",
        "summary": "© Ronald Tilleman\n\n\n\t\t\n      Architects: Studio Marco Vermeulen\n\t\t\n\t\t\n      Location: Bezoekerscentrum Biesbosch-Museumpad, 3313 Dordrecht, Netherlands\n\t\t\n\t\t\n      Area: 1300.0 sqm\n\t\t\n\t\t\n      Project Year: 2015\n\t\t\n\t\t\n      Photographs: Ronald Tilleman\n\t\t\n\n\n    \n      \n    \n    ...",
        "title": "Biesbosch Museum Island / Studio Marco Vermeulen",
        "link": "http://feedproxy.google.com/~r/ArchDaily/~3/K8MCE4rdZwQ/biesbosch-museum-island-studio-marco-vermeulen",
        "feed": "ArchDaily",
        "published": "Fri, 27 Nov 2015 08:00:00 GMT",
        "image": "http://images.adsttc.com/media/images/5656/8185/e58e/ceb2/5f00/026d/medium_jpg/portada_SMV_View_Exterior_09_%C2%A9Ronald_Tilleman_MR.jpg?1448509815",
        "diff": "2 days",
        "websiteUrl": "http://www.archdaily.com/",
        "websiteDesc": "ArchDaily | Broadcasting Architecture Worldwide",
        "whenLastUpdate": "Fri, 27 Nov 2015 08:05:45 GMT"
    }
]
}
